// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Y3zjqh3wSfUNvx_vjECrdc9Lah2BwUU',
    appId: '1:364938733915:web:1fd05938590dd8dd7f127e',
    messagingSenderId: '364938733915',
    projectId: 'firstproject-67190',
    authDomain: 'firstproject-67190.firebaseapp.com',
    databaseURL: 'https://firstproject-67190-default-rtdb.firebaseio.com',
    storageBucket: 'firstproject-67190.firebasestorage.app',
    measurementId: 'G-PL2MBQR2GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMtJOhlm-sSmLNI5dCGJaF6V7sBYJH410',
    appId: '1:364938733915:android:7d77d863fceb7d287f127e',
    messagingSenderId: '364938733915',
    projectId: 'firstproject-67190',
    databaseURL: 'https://firstproject-67190-default-rtdb.firebaseio.com',
    storageBucket: 'firstproject-67190.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAJHXg3dfjdAi2SNiEUQJm5mi4m1SbfTI',
    appId: '1:364938733915:ios:a33232ab7e5b63657f127e',
    messagingSenderId: '364938733915',
    projectId: 'firstproject-67190',
    databaseURL: 'https://firstproject-67190-default-rtdb.firebaseio.com',
    storageBucket: 'firstproject-67190.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAJHXg3dfjdAi2SNiEUQJm5mi4m1SbfTI',
    appId: '1:364938733915:ios:a33232ab7e5b63657f127e',
    messagingSenderId: '364938733915',
    projectId: 'firstproject-67190',
    databaseURL: 'https://firstproject-67190-default-rtdb.firebaseio.com',
    storageBucket: 'firstproject-67190.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );
}
