const personalViewRoute='/personalView';
const workViewRoute='/workView';
const writePersonalViewRoute='/writePersonal';
const writeWorkViewRoute='/writeWork';
const registerViewRoute= '/registerViewRoute';
const loginViewRoute= '/loginViewRoute';
const myAppViewRoute='/myAppViewRoute';
const familyViewRoute='/familyViewRoute';
const writeFamilyViewRoute='/writeFamilyViewRoute';